var GAME_LEVELS = [
  ["                                v                                        v   v  ",
   "                                                                                ",
   "                                           o                              v v   ",
   "                     m     o             yyx   yyy             xxxx        v    ",
   "             yy     yyy    x    yyy      xxx   y yy           x  xxx            ",
   "     yyy    yyyyy   y yy  xx   yy y   yyyxxyyy   yy          m    xxx           ",
   "    yy y  yyyyyyyyy   yy xxx   yy   yyyxxxyyyyyyyy  o             xxx           ",
   "    yy   yyyyyyyyyyyyyy xxxx    yyyyyyxxxy         xx            xxxxx          ",
   "     yyyyyyyyyy         xxxx         xxxx    xx           xx     xxxxx          ",
   "                       xxxxx        xxxxx                       xxxxxx          ",
   "                  o   xxxxxx       xxxxx                          o             ",
   "                  s   xxxxxx       xxxxx                                        ",
   "                 sss  xxxxxx       xxxxxxx                     xxxxxxx          ",
   "                  x  xxxxxxx       xxxxxxxx                    xxxxxxxxx        ",
   "s         s      xxxxxxxxxxx s    xxxxxxxxx                   pxxxxxxxx    o    ",
   "ss       sss    xxxxxxxxxxxxsss   xxxxxxxxxp                  pxxxxxxx          ",
   "x    @    x         xxxxxxxx x   pxxxxxxxxxp                xxxxxxxxxxx         ",
   "xxxxxxxxxxx      xxxxxxxxxxxxx   pxxxxxxxxxxx               xxxxxxxxxxx         ",
   "          x     x    x    x   x  xx     x    x             x              xxx   ",
   "          x!!!!!x    x    x   x!!!x     x    x!!!!!!!!!!!!!x                    ",
   "          x!!!!!x    x    x   x!!!x     x    x!!!!!!!!!!!!!x                    ",
   "           xxxxx               xxx            xxxxxxxxxxxxx                     ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                              s   ",
   "                                                                   xxxxxx                                    sss  ",
   "                                                                  xx     xx                          o        x   ",
   "                         yy     yyy                              xx                                  s       x!x  ",
   "                yyy     yyyyy   y yy                             x    o         xxxxx               sss      x!x  ",
   "               yy y   yyyyyyyyy   yy                             x    s                          =   x       x!x  ",
   "               yy    yyyyyyyyyyyyyy                              xx  sss  |                   xxxxxxxxxxxxxxx!!x  ",
   "                yyyyyyyyyy       vvv                            m xx  x  xx                                       ",
   "                                                                   xxxxxx              xxx                        ",
   "                                                                                    s                             ",
   "                      o                                                            sss                            ",
   "                     xx                                                             x                             ",
   "                    xxxx                                                        xxxxx                             ",
   "                   xxx  xx                                                         v                              ",
   "                  xxxx   x                                     o              xx                                  ",
   "                 xxxxxx                                        s             xxxx                                 ",
   "                 xxxxxx                                       sss           xxxxxx                                ",
   "                xxxxxxx        x  o  x                         x           xxxxxxx                                ",
   "               xxxxxxxx                                      xxxx         xxxxxxxxx                               ",
   "     @         xxxxxxxxx                                                 xxxxxxxxxx                               ",
   "    xxx        xxxxxxxxx          o                                                                               ",
   "    xxx        xxxxxxxxx                                  x                             o    p                    ",
   "    xxx       pxxxxxxxxx!                                   !!!     x             = x   s    p                    ",
   "    xxx       pxxxxxxxxxx!                                !!!xx!    xxxxxxxxxxxxxxxx   sss   x                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxxx!     s                    xx   !!!xxx!                    xx  x  xx                     ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!    sss                       !!!xxxx!                      xxxxx                       ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!    x         x    x       !!!!xxxxx!                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xxxxx!!!                                                 ",
   "!!!! x xxxxxx  xxx  xxx  xxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxx!!!!!!                                                "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                       o             ",
   "                                        s                                                      oso            ",
   "                                       sss                                                    ossso           ",
   "                                        x          xxx                                         oxo            ",
   "                                        x     x              xxx                         xxxxxxxxxxxxxxx      ",
   "                                       xxx                                          m                         ",
   "                                       x!!!                                xxx                                ",
   "                                       xxx!!                                                                  ",
   "                                      xxxxx!                        s                 xxx                     ",
   "                                    s xxxxx!!                      sss                                        ",
   "              s                    sssxxxxxx!!                      x                                         ",
   "             sss                    x xxxxxx!!!                xxxxxxxxx       xxx                            ",
   "              x                    xxxxxxxxxxx!!!!x          xxx                                              ",
   "       xxxxxxxxx                    xxxxxxxxxxxxxxx         xxx                                               ",
   "                                   pxxxxxxxp               xx                                                 ",
   "                                   pxxxxxxxp               xxx              xxx                               ",
   "                                   xxxxxxxxxxx            xxxx                                                ",
   "                                   xxxxxxxx      =        xxxx                                                ",
   "                                  xxxxxxxxx        xxx    pxxx                                                ",
   "                                 xxxxxxxxxx               pxxxx    xxx                    p                   ",
   "                                m v  xxxxxxxx             xxxxx                           p                   ",
   "                                      xxxxx         xxx    xxxx              xxx        xxx                   ",
   "                                     oxxxxxo               xxxxx                       m                      ",
   "                             xxx    xxxxxxxxx              xxxxxx                                             ",
   "                            xxxxxx     xxxxx              =xxxxxxxxx                                      s   ",
   "                           xxxxxx         xx      xxxxxxxxxxxxxxxxxxxxx                                  sss  ",
   "  !                        xxxxx          xx                                                              x   ",
   "  x!                      xxxxxx    x     xxx                                                            xxx  ",
   "  x!                     xxxxxxx    x     xxxx                                                             x  ",
   "  x!                    xxxxxxxx   xxx   xxxxxxxx                        o                                 x  ",
   "  x!                   xxxxxxxxx          x            xxppxx            s                                 x  ",
   "  x!                   xxxxxxxxx          x         xxxx    xxxx        sss                      o         x  ",
   "  x!                  xxxxxxxxxxxx        x        xxx |    | xxx        x          xxx          s         x  ",
   "  x!                 xxxxxxxxxxx   o o           xxxx          xxxx      x                      sss        x  ",
   "  x!              xxxxxxxxxxxxxx                                        xxx                      x         x  ",
   "  x!             xxxxxxxxxxxxxx    xxx                                  xxx                     xxx        x  ",
   "  x!!         xxxxxxxxxxxxxxxxx!!!xxxxx!!xx     xxx    x    x    x     xxxxx                    xxx        x  ",
   "  x!!!   @  xxxxxxxxxxxxxxxxxxx   x   x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x   x    xxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                  x   x                                                                       ",
   "                                  x   x                                                                       "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                 p            ",
   "                         @                                                                       p            ",
   "      xxx     xxx      xxxxx     xxx     xxx             xxxx     xxxx    xxxxxxxxx     xxx    xxx            ",
   "       xx     xx      xx   xx     xx     xx                xx     xx       xxxxxxx      xxxx   xx             ",
   "        x     x      xxx   xxx    xx     xx   x        x   xx  x  xx         xxx        xxxxx  xx             ",
   "        xx   xx      xxx   xxx    xx     xx                xx xxx xx         xxx        xx  xxxxx             ",
   "         xxxxx       xxx   xxx    xx     xx      xxxx      xx xxx xx         xxx        xx   xxxx             ",
   "          xxx        xxx   xxx    xxx   xxx                xxxxxxxxx         xxx        xx    xxx             ",
   "          xxx         xx   xx      xx   xx                 xxxx xxxx       xxxxxxx      xx    xxx             ",
   "          xxx          xxxxx        xxxxx                   xx   xx       xxxxxxxxx    xxx     xx             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
